---
- name: Common setup
  hosts: all
  remote_user: "{{ remote_user }}"
  tags: common
  roles:
    - common

- name: Set timedate
  hosts: all
  remote_user: "{{ remote_user }}"
  tags: timedate
  roles:
    - timedate

- name: Update hostname and populate /etc/hosts
  hosts: all
  remote_user: "{{ remote_user }}"
  tags: hostname
  roles:
    - hostname

- name: Join Active Directory
  hosts: all
  remote_user: "{{ remote_user }}"
  tags: ad
  roles:
    - role: ad
      when: auth_backend == "ad"

- name: Set up LDAP
  hosts: all
  remote_user: "{{ remote_user }}"
  tags: ldap
  roles:
    - role: ldap
      when: auth_backend == "ldap"

- name: Set up NFS
  hosts: all
  remote_user: "{{ remote_user }}"
  tags: nfs
  roles:
    - nfs

- name: Set up Lmod
  hosts: all
  remote_user: "{{ remote_user }}"
  tags: lmod
  roles:
    - lmod

- name: Set up Slurm
  hosts: all
  remote_user: "{{ remote_user }}"
  tags: slurm
  roles:
    - slurm

- name: Set up Open OnDemand
  hosts: login
  remote_user: "{{ remote_user }}"
  tags: openondemand
  roles:
    - openondemand

- name: Install cluster packages
  hosts: controller
  remote_user: "{{ remote_user }}"
  tags: package
  roles:
    - package
