---
- name: Restart nslcd
  become: true
  ansible.builtin.service:
    name: nslcd
    state: restarted
    enabled: true

- name: Restart apache2
  become: true
  ansible.builtin.service:
    name: apache2
    state: restarted
    enabled: true
