---
- name: Ensure debconf-utils is installed for controller
  become: true
  ansible.builtin.package:
    name: debconf-utils
    state: present
  when: "'controller' in group_names"
  tags: [ldap, ldap-controller]

- name: Pre-seed slapd debconf for controller
  become: true
  ansible.builtin.debconf:
    name: slapd
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  loop:
    - question: "slapd/no_configuration"
      value: "false"
      vtype: "boolean"
    - question: "slapd/domain"
      value: "{{ ldap_domain }}"
      vtype: "string"
    - question: "slapd/organization"
      value: "{{ ldap_org }}"
      vtype: "string"
    - question: "slapd/password1"
      value: "{{ ldap_password }}"
      vtype: "password"
    - question: "slapd/password2"
      value: "{{ ldap_password }}"
      vtype: "password"
    - question: "slapd/backend"
      value: "MDB"
      vtype: "select"
    - question: "slapd/purge_database"
      value: "true"
      vtype: "boolean"
    - question: "slapd/move_old_database"
      value: "true"
      vtype: "boolean"
  when: "'controller' in group_names"
  tags: [ldap, ldap-controller]

- name: Set up LDAP authentication with TLS for controller
  ansible.builtin.include_tasks: ldap-controller.yml
  when: "'controller' in group_names"
  tags: [ldap, ldap-controller, phpldapadmin]

- name: Set up LDAP authentication for compute node
  ansible.builtin.include_tasks: ldap-node.yml
  when: "'nodes' in group_names"
  tags: [ldap, ldap-node]
