---
- name: Install required packages
  become: true
  ansible.builtin.package:
    name:
      - phpldapadmin
    state: present
  tags: [ldap, phpldapadmin]

- name: Configure phpLDAPadmin
  become: true
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: www-data
    mode: "644"
  loop:
    - src: phpldapadmin-config.php.j2
      dest: /etc/phpldapadmin/config.php
    - src: generalUser.xml.j2
      dest: /usr/share/phpldapadmin/templates/creation/generalUser.xml
  notify: Restart apache2
  tags: [ldap, phpldapadmin]
