---
- name: Check if munge.key exists
  become: true
  ansible.builtin.stat:
    path: /etc/munge/munge.key
  register: slurm_munge_key
  tags: [slurm, slurm-controller]

- name: Generate munge.key
  ansible.builtin.command: /usr/sbin/mungekey
  when: not slurm_munge_key.stat.exists
  changed_when: not slurm_munge_key.stat.exists

  notify: Restart slurmctld
  tags: [slurm, slurm-controller]

- name: Set ownership of munge.key
  become: true
  ansible.builtin.file:
    path: /etc/munge/munge.key
    owner: munge
    group: munge
  when: not slurm_munge_key.stat.exists
  notify: Restart slurmctld
  tags: [slurm, slurm-controller]

- name: Set up Slurmdbd
  ansible.builtin.include_tasks: slurmdbd-controller.yml
  when: slurm_acct | bool
  tags: [slurm, slurmdbd-controller]

- name: Copy over slurm.conf
  become: true
  ansible.builtin.template:
    src: slurm.conf.j2
    dest: /etc/slurm/slurm.conf
    owner: slurm
    group: slurm
    mode: "644"
  notify: Restart slurmctld
  tags: [slurm, slurm-controller]

- name: Copy over cgroup.conf
  become: true
  ansible.builtin.template:
    src: cgroup.conf.j2
    dest: /etc/slurm/cgroup.conf
    owner: slurm
    group: slurm
    mode: "644"
  notify: Restart slurmctld
  tags: [slurm, slurm-controller]

- name: Create slurm spool directory
  become: true
  ansible.builtin.file:
    path: /var/spool/slurm
    state: directory
    owner: slurm
    group: slurm
    mode: "755"
  notify: Restart slurmctld
  tags: [slurm, slurm-controller]

- name: Create slurmctld.log
  become: true
  ansible.builtin.file:
    path: /var/log/slurmctld.log
    state: touch
    owner: slurm
    group: slurm
    mode: "644"
  notify: Restart slurmctld
  tags: [slurm, slurm-controller]

- name: Set up OpenMPI
  ansible.builtin.include_tasks: openmpi.yml
  tags: [slurm, openmpi]
