---
- name: Install Realmd dependencies
  become: true
  ansible.builtin.package:
    name:
      - realmd
      - samba-common-bin
      - adcli
    state: present
  tags: [ad, realmd]

- name: Preconfigure some krb5.conf settings
  become: true
  ansible.builtin.blockinfile:
    path: /etc/krb5.conf
    mode: "644"
    create: true
    block: |
      [libdefaults]
        rdns = false
        default_realm = {{ ad_domain | upper }}
        udp_preference_limit = 0
    marker: "# {mark} ANSIBLE MANAGED"
  when: not ad_rdns | bool
  tags: [ad, realmd]

- name: Set permissions on krb5.conf
  become: true
  ansible.builtin.file:
    path: /etc/krb5.conf
    owner: root
    group: root
    mode: "644"
  when: ad_rdns == "false"
  tags: [ad, realmd]

- name: Check realm status
  ansible.builtin.command: realm list
  register: ad_realm_status
  changed_when: false
  tags: [ad, realmd]

- name: Join AD domain
  become: true
  ansible.builtin.shell: |
    set -o pipefail
    echo '{{ ad_password }}' | realm join --user={{ ad_user }} {{ ad_domain }}
  args:
    executable: /bin/bash
  when: ad_domain not in ad_realm_status.stdout
  changed_when: ad_domain not in ad_realm_status.stdout
  tags: [ad, realmd]
