---
- name: Install SSSD dependencies
  become: true
  ansible.builtin.package:
    name:
      - sssd
      - sssd-tools
      - libnss-sss
      - libpam-sss
      - samba-common-bin
  tags: sssd

- name: Reconfigure existing SSSD options
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    path: /etc/sssd/sssd.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertafter: "{{ item.insertafter | default(omit) }}"
    state: present
  loop:
    - regexp: "^use_fully_qualified_names ="
      line: "use_fully_qualified_names = False"
    - regexp: "^#?fallback_homedir ="
      line: "#fallback_homedir = /home/%u@%d"
  notify: Restart sssd
  tags: [ad, sssd]

- name: Set homedir in SSSD
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sssd/sssd.conf
    insertafter: '\[domain/{{ ad_domain }}\]'
    line: "override_homedir = /home/%u"
  notify: Restart sssd
  tags: [ad, sssd]

- name: Ensure pam_mkhomedir is configured in common-session
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pam.d/common-session
    line: "session required pam_mkhomedir.so skel=/etc/skel/ umask=0022"
    insertafter: "^session.+pam_sss.so"
    state: present
  notify: Restart sssd
  tags: [ad, sssd]
