---
ood_release_deb: "https://apt.osc.edu/ondemand/4.0/ondemand-release-web_4.0.0-noble_all.deb"
ood_release_file: "/tmp/ondemand-release-web_4.0.0-noble_all.deb"
ood_cert_dir: "/etc/ood/cert"
ood_config_dir: "/etc/ood/config"
ood_script_dir: "/etc/ood/script"
ood_home_script: "/etc/ood/script/home.sh"
ood_cert_days: "3650"
