---
- name: Restart slurmctld
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: restarted
  loop:
    - munge
    - slurmctld

- name: Restart slurmd
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: restarted
  loop:
    - munge
    - slurmd
