---
- name: Restart slurmctld
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: restarted
  loop:
    - munge
    - slurmctld

- name: Restart slurmd
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: restarted
  loop:
    - munge
    - slurmd

- name: Start MariaDB
  become: true
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true

- name: Enable slurmdbd
  become: true
  ansible.builtin.service:
    name: slurmdbd
    state: started
    enabled: true
  when: "'nodes' in group_names"
