---
- name: Update apt cache (Debian/Ubuntu)
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_facts.os_family == "Debian"

- name: Update yum cache (RHEL/CentOS)
  become: true
  ansible.builtin.dnf:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_facts.os_family == "RedHat"

- name: Install dependencies for ansible
  become: true
  ansible.builtin.package:
    name:
      - python3-pexpect
    state: present
  tags: common
