---
- name: R
  ansible.builtin.include_tasks: r.yml
  when: "'controller' in group_names"
  tags: [package, r]

- name: RStudio
  ansible.builtin.include_tasks: rstudio.yml
  tags: [package, rstudio]

- name: Python
  ansible.builtin.include_tasks: python.yml
  when: "'controller' in group_names"
  tags: [package, python]

- name: Jupytherhub
  ansible.builtin.include_tasks: jupyterhub.yml
  when: "'controller' in group_names"
  tags: [package, jupyterhub]
